#1)TO DO LIST

print("TO DO LIST")
Month=str(input("Enter the month:"))
print(Month)
Date=str(input("Enter the date:"))
print(Date)
#from datetime import date
#today = date.today()
#print(today)
heading=Month+" "+Date
print("Month:", Month +"    "+"Date:",Date)
print("\nTO DO")
list_1=[]
Task_1=input("Enter task 1:")
list_1.append(Task_1)
Task_2=input("Enter task 2:")
list_1.append(Task_2)
Task_3=input("Enter task 3:")
list_1.append(Task_3)
Task_4=input("Enter task 4:")
list_1.append(Task_4)
Task_5=input("Enter task 5:")
list_1.append(Task_5)
Task_6=input("Enter task 6:")
list_1.append(Task_6)
Task_7=input("Enter task 7:")
list_1.append(Task_7)
Task_8=input("Enter task 8:")
list_1.append(Task_8)
Task_9=input("Enter task 9:")
list_1.append(Task_9)
Task_10=input("Enter task 10:")
list_1.append(Task_10)
print("Today's tasks are:")
print("\n".join(list_1))

print("\n PRIORITIES")
list_2=[]
Priority_1=input("Enter priority 1:")
list_2.append(Priority_1)
Priority_2=input("Enter priority 2:")
list_2.append(Priority_2)
Priority_3=input("Enter priority 3:")
list_2.append(Priority_3)
Priority_4=input("Enter priority 4:")
list_2.append(Priority_4)
Priority_5=input("Enter priority 5:")
list_2.append(Priority_5)
print("Today's priorities are:")
print("\n".join(list_2))

print("\n NOTES")
N=input("Write your notes here:")
print("Today's note:", N)

print("\n REMINDER")
R=input("Write your reminder here:")
print("Today's Reminder:", R)
